Traceback (most recent call last):
  File "/home/docker/new_docker_supervisord/apps/app_05/main.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
Traceback (most recent call last):
  File "/home/docker/new_docker_supervisord/apps/app_05/main.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
Traceback (most recent call last):
  File "/home/docker/new_docker_supervisord/apps/app_05/main.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
Traceback (most recent call last):
  File "/home/docker/new_docker_supervisord/apps/app_05/main.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
